### ISSUE TITLE
Can't start chrome executable: Segmentation Fault

### ISSUE THREAD

**Issue by promethial** [leo-lb/ungoogled-chromium#10]
I'm unable to run the Chrome executable, running it results in a Segmentation fault. This is leveraging a pre-built executable from the CI/CD pipeline (pipeline #90422547). Not a very descriptive error, but it's pasted below.

`[1]    12665 segmentation fault  ./chrome`

OS: Debian Buster
Platform: IBM Power9

**Comment by leo-lb** [comment]
Please try compiling on your own, CI/CD binaries are NOT static linked and are likely to work only on the system version they were built on (Ubuntu Bionic) with the build dependencies installed, but do not that in the current state of things, these binaries also work on Fedora 30.

**Comment by promethial** [comment]
Didn't realize that was the case. Will try that, thanks!
