### ISSUE TITLE
Integrated PDF reader does not work

### ISSUE THREAD

**Issue by leo-lb** [leo-lb/ungoogled-chromium#2]
Should look into the patches, why they do not apply, and incorporate them again in the patch list after fixing.

**Comment by darkbasic** [comment]
Any news on this?

**Comment by leo-lb** [comment]
@darkbasic Fixed by https://github.com/leo-lb/ungoogled-chromium/commit/78aa3a558b735a66b0cee8f45cf62840a21d8920 and https://github.com/leo-lb/ungoogled-chromium/commit/3c8d660eb05914b2f7f78de75709f89f90a3dacf

**Comment by darkbasic** [comment]
Thank you!
