### ISSUE TITLE
Installing extensions gives CRX_HEADER_INVALID

### ISSUE THREAD

**Issue by leo-lb** [leo-lb/ungoogled-chromium#3]

**Comment by snakyjake1** [comment]
I'm getting the same error/problem why I try to install an extension.
Tried using Google Chrome, and get the same error/problem.

**Comment by leo-lb** [comment]
> I'm getting the same error/problem why I try to install an extension.
> Tried using Google Chrome, and get the same error/problem.

Google Chrome is not available for ppc64le, I assume you mean Chromium with the ppc64le patches applied? I suppose @shawnanastasio might know more about this.

**Comment by snakyjake1** [comment]
I have another machine with Google Chrome installed (v73.0.3683.103), and was getting the same problem.

I think there's something going on with Google's CRX format (CRX2 vs CRX3).
I would try getting the CRX2 format and try installing.

**Comment by shawnanastasio** [comment]
Extension installation on upstream chromium + the ppc64le patches works as expected, so I'm inclined to believe the issue lies with the ungoogled patchset and isn't directly related to the ppc64le patches.

**Comment by leo-lb** [comment]
@shawnanastasio Which version?

**Comment by leo-lb** [comment]
I'm going to rebase on upstream, they released 74.x - and see if the issue is still present.

**Comment by shawnanastasio** [comment]
@leo-lb I tested on 75.0.3731.0

**Comment by leo-lb** [comment]
Same error on ungoogled-chromium ppc64le 74.0.3729.108

**Comment by leo-lb** [comment]
Ends up being a non-issue, using crx extensions from this link fixes the issue: `https://clients2.google.com/service/update2/crx?response=redirect&os=win&arch=x86-64&os_arch=x86-64&nacl_arch=x86-64&prod=chromiumcrx&prodchannel=unknown&prodversion=73.0.3683.86&acceptformat=crx2,crx3&x=id%3D[EXTENSION_ID]%26uc`

Replace `[EXTENSION_ID]` by the extension ID, it can be found in the chrome web store url.
