### ISSUE TITLE
Block URL in URLRequest errors prevent browsing to many common sites

### ISSUE THREAD

**Issue by Slime90** [leo-lb/ungoogled-chromium#8]
**Describe the bug**
When browsing to many common websites, a "Block URL in URLRequest errors" message occurs and the page crashes
![chrom77error](https://user-images.githubusercontent.com/56482677/66704002-30fc8700-ece6-11e9-8f6d-7dc67de3c2e7.jpg)

[15871:15914:1012/113635.764133:ERROR:url_request.cc(626)] Block URL in URLRequest: https://support.9oo91e.qjz9zk/chrome/?p=e_awsnap
[15871:15914:1012/113635.764214:ERROR:trk_protocol_handler.cc(17)] Blocked URL in TrkProtocolHandler: trk:https://support.9oo91e.qjz9zk/chrome/?p=e_awsnap
[15871:15914:1012/114036.624655

**Expected behavior**
On the release version of ungoogled-chromium 74, and others I have used on non PPC platforms, this happens in the background and does not interrupt browsing.

**Environment (please complete the following information):**
 - OS/Platform and version: Ubuntu 19.04 up to date, running on a Talos Blackbird
 - ungoogled-chromium version: Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by leo-lb** [comment]
@Slime90 This is ungoogled-chromium, not Chromium, lots of URLs pointing to Google are purposefully blocked. If you want to suggest changing this behavior, see this with upstream: https://github.com/Eloston/ungoogled-chromium
